version: '3.9'
services:
  db:
    restart: always
    image: "postgres:15.0"
    container_name: db
    volumes:
      - ./database/:var/lib/postgresql/data
    environment:
      PGDATA: "/var/lib/postgresql/pgdata"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRESDB: postgres
    ports:
      - 5433:5432

  api:
    restart: always
    build: ./api
    env_file:
      - .env
    command: "uvicorn main:app --reload --workers 4 --host 0.0.0.0 --port 8000"
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - ./api:/api